### ISSUE TITLE
Time service not sending timingcontrol messages

### ISSUE THREAD

**Issue by e-tinus** [DRIVER-EU/test-bed-time-service#19]
I'm not sure if this should be the case, but when cleaning the C# adapter (and adding new functionalities to update the application with timing control changes) I found the time service not sending out the timing control messages (https://github.com/DRIVER-EU/avro-schemas/blob/master/core/time/system_timing_control-value.avsc).

**Comment by erikvullings** [comment]
But why should the time service send out these messages? It just listens to them.
Or do you mean the gui? But the gui is solely intended to show the clock, and manipulating the time is only a debugging feature.

**Comment by e-tinus** [comment]
Ah OK, so the Trial Management Tool is sending out the timing control messages, to be picked up by all adapters (including the one attached to the time service). I was testing the timing control messages via the time service (since it also allows for changing the time speed for instance), but I need to test this via the TMT then, correct?

**Comment by erikvullings** [comment]
Indeed, in case you want to listen to the timing control messages yourself,
you do need to use the TMT, as that's the only service that is sending them
ATM.
