### ISSUE TITLE
Publish new docker version of the test-bed-time-service

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed-time-service#9]
And inform me how to do it too ;-)

**Comment by erikvullings** [comment]
Moved config to webpack and npm i, as parcel and pnpm gave some issues in the Docker container.

**Comment by PHameete** [comment]
So you can now publish a new image automatically with npm?

Shall I still set up Travis for automatic builds? If so: make a new issue for that :-)
